# Generated by Django 2.2 on 2019-09-19 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=200, verbose_name='Last Name')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('valid_id', models.IntegerField(choices=[(1, 'SSS'), (2, 'PAGIBIG'), (3, 'PHILHEALTH'), (4, 'HUMID'), (5, 'PASSPORT'), (6, 'VOTERS_ID')], verbose_name='Valid ID')),
                ('collaterals', models.CharField(max_length=200, verbose_name='Collaterals')),
                ('loan_amount', models.FloatField(verbose_name='Loan Amount')),
            ],
        ),
    ]
